# mysql
mysqlserver:
  image: drvitamina/ea-mysql:5.6.27
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: stepmaildev
# php
phpserver:
  image: drvitamina/ea_php:5.5.30-apache
  volumes:
    - ~/Documents/workspace/ea_sales_management/trialuser-stepmail:/var/www/html
  links:
    - mysqlserver
  ports:
    - "80:80"
    - "443:443"
